export const ghanaUniversities = [
  {
    name: "University of Ghana (UG)",
    ranking: 1,
    image: "picture/ug_campus.jpg",
    type: "Public",
    location: "Legon, Accra",
    established: 1948,
    academicsInfo: "Renowned for its liberal arts, humanities, law, basic and applied sciences, and medicine. It is the premier and largest university in Ghana.",
    performanceReview: "Highly ranked in West Africa for research productivity, citation impact, and international collaboration.",
    feesRange: "GH₵ 3,500 - GH₵ 7,500 / year",
    scholarshipsInfo: "UG Financial Aid Office, MasterCard Foundation Scholars Program, and various corporate bursaries.",
    programsOffered: ["Bachelor of Laws (LLB)", "BSc Computer Science", "Bachelor of Medicine and Surgery", "BSc Business Administration", "BSc Nursing", "BA Political Science"],
    admissionRequirements: "WASSCE: Credit passes (A1-C6) in 3 core subjects (Maths, English, Science/Social) plus 3 electives. Aggregate total must be 24 or lower."
  },
  {
    name: "Kwame Nkrumah University of Science and Technology (KNUST)",
    ranking: 2,
    image: "picture/knust_campus.jpg",
    type: "Public",
    location: "Kumasi, Ashanti Region",
    established: 1951,
    academicsInfo: "The leading institution in science and technology education in Ghana. Strong programs in engineering, architecture, pharmacy, and physical sciences.",
    performanceReview: "Exceptional output in technical innovations, research patents, and engineering engineering projects in Sub-Saharan Africa.",
    feesRange: "GH₵ 3,800 - GH₵ 8,500 / year",
    scholarshipsInfo: "MasterCard Foundation, Vice-Chancellor's Fund, and GETFund local bursaries.",
    programsOffered: ["BSc Civil Engineering", "BSc Computer Engineering", "BSc Architecture", "Doctor of Pharmacy", "BSc Mechanical Engineering", "BSc Aerospace Engineering"],
    admissionRequirements: "WASSCE: Credits in English, Core Maths, Integrated Science, and 3 Electives in related sciences (Physics, Chemistry, Applied Maths) with aggregate <= 24."
  },
  {
    name: "University of Cape Coast (UCC)",
    ranking: 3,
    image: "picture/ucc_campus.jpg",
    type: "Public",
    location: "Cape Coast, Central Region",
    established: 1962,
    academicsInfo: "Famous for teacher training, business, agriculture, development studies, and medical science education.",
    performanceReview: "Consistently ranked as the top university in Ghana for research influence and pedagogical training.",
    feesRange: "GH₵ 3,400 - GH₵ 7,200 / year",
    scholarshipsInfo: "UCC Student Financial Support Office, local district assembly sponsorships, and Kakum bursaries.",
    programsOffered: ["BEd Computer Science", "BSc Accounting and Finance", "Bachelor of Medicine", "BSc Optometry", "BSc Molecular Biology", "BA Development Studies"],
    admissionRequirements: "WASSCE: Credits in English, Core Maths, Science/Social, and 3 electives with aggregate total <= 24."
  },
  {
    name: "University for Development Studies (UDS)",
    ranking: 4,
    image: "picture/uds_campus.jpg",
    type: "Public",
    location: "Tamale, Northern Region",
    established: 1992,
    academicsInfo: "Pioneered the third-trimester practical field program. Specialized in agriculture, medicine, allied health sciences, and development studies.",
    performanceReview: "High community impact through student-led rural development audits and community service programs.",
    feesRange: "GH₵ 2,800 - GH₵ 6,000 / year",
    scholarshipsInfo: "Northern Development Authority grants, WHO health study sponsorships, and UDS financial aid program.",
    programsOffered: ["Doctor of Medicine (MD)", "BSc Agriculture", "BSc Development Studies", "BSc Community Nutrition", "BSc Nursing (Public Health)"],
    admissionRequirements: "WASSCE: Credit passes (A1-C6) in English, Core Maths, Integrated Science, and 3 electives with aggregate total <= 24."
  },
  {
    name: "University of Education, Winneba (UEW)",
    ranking: 5,
    image: "picture/uew_campus.jpg",
    type: "Public",
    location: "Winneba, Central Region",
    established: 1992,
    academicsInfo: "Specialized in training teachers and education professionals for basic and secondary schools in Ghana.",
    performanceReview: "Recognized as the primary driver of national teacher training, pedagogy development, and educational research.",
    feesRange: "GH₵ 2,900 - GH₵ 5,500 / year",
    scholarshipsInfo: "GETFund support, UEW institutional bursaries, and local municipal teacher financial aids.",
    programsOffered: ["BEd Mathematics Education", "BEd English Education", "BSc Information Technology Education", "BA Music Education", "BEd Special Education"],
    admissionRequirements: "WASSCE: Credit passes in English, Core Maths, Science/Social, plus 3 relevant teaching electives."
  },
  {
    name: "Ghana Institute of Management and Public Administration (GIMPA)",
    ranking: 6,
    image: "picture/gimpa_campus.jpg",
    type: "Public",
    location: "Greenhill, Accra",
    established: 1961,
    academicsInfo: "Elite business school specializing in public administration, corporate governance, information technology management, and law.",
    performanceReview: "Voted top executive school in Ghana, popular with public sector leaders and working corporate managers.",
    feesRange: "GH₵ 6,000 - GH₵ 12,000 / year",
    scholarshipsInfo: "GIMPA Corporate Executive Sponsorships, public service staff training packages, and merit bursaries.",
    programsOffered: ["Bachelor of Laws (LLB)", "BSc Business Administration", "BSc Information Technology", "Master of Public Administration (MPA)", "BSc Finance"],
    admissionRequirements: "WASSCE: Minimum of 6 credit passes (A1-C6) including English and Core Mathematics. Post-diploma entry available."
  },
  {
    name: "University of Professional Studies, Accra (UPSA)",
    ranking: 7,
    image: "picture/upsa_campus.jpg",
    type: "Public",
    location: "Madina, Accra",
    established: 1965,
    academicsInfo: "Blends academic excellence with professional practice. Major courses in marketing, accounting, public relations, and business administration.",
    performanceReview: "Renowned for high professional exam pass rates (ICAG, ACCA, CIM) among students.",
    feesRange: "GH₵ 3,200 - GH₵ 6,800 / year",
    scholarshipsInfo: "UPSA Vice Chancellor Endowment Fund (VCEF), corporate financial sponsorships, and local union grants.",
    programsOffered: ["BSc Accounting", "BSc Marketing", "BSc Business Economics", "BSc Public Relations Management", "BSc Information Technology"],
    admissionRequirements: "WASSCE: 3 credit passes in core subjects (Maths, English, Science) plus 3 electives in related business tracks."
  },
  {
    name: "University of Mines and Technology (UMaT)",
    ranking: 8,
    image: "picture/umat_campus.jpg",
    type: "Public",
    location: "Tarkwa, Western Region",
    established: 2004,
    academicsInfo: "Highly specialized mining engineering institution. Courses cover mineral extraction, geological sciences, petroleum engineering, and environmental safety.",
    performanceReview: "World-class laboratory facilities and nearly 100% employment rate for graduates in global mining corporations.",
    feesRange: "GH₵ 3,900 - GH₵ 8,200 / year",
    scholarshipsInfo: "Ghana Chamber of Mines Scholarships, mining corporate sponsorships (Newmont, Gold Fields), and local development aids.",
    programsOffered: ["BSc Mining Engineering", "BSc Geological Engineering", "BSc Petroleum Engineering", "BSc Mineral Engineering", "BSc Geomatic Engineering"],
    admissionRequirements: "WASSCE: Credit passes in English, Core Maths, Physics, Chemistry, and Elective Maths."
  },
  {
    name: "University of Health and Allied Sciences (UHAS)",
    ranking: 9,
    image: "picture/uhas_campus.jpg",
    type: "Public",
    location: "Ho, Volta Region",
    established: 2011,
    academicsInfo: "Dedicated exclusively to health professional training, research, and community service. Medicine, pharmacy, nursing, public health, and therapy.",
    performanceReview: "Highly competitive admission entries and strong clinical training partnerships with local teaching hospitals.",
    feesRange: "GH₵ 4,200 - GH₵ 9,000 / year",
    scholarshipsInfo: "Ministry of Health bursaries, Volta Region development grants, and UHAS corporate endowments.",
    programsOffered: ["Bachelor of Medicine & Surgery", "Doctor of Pharmacy (PharmD)", "BSc General Nursing", "BSc Public Health", "BSc Medical Laboratory Science"],
    admissionRequirements: "WASSCE: Strict credit passes in English, Core Maths, Integrated Science, Biology, Chemistry, and Physics with aggregate <= 15."
  },
  {
    name: "University of Energy and Natural Resources (UENR)",
    ranking: 10,
    image: "picture/uenr_campus.jpg",
    type: "Public",
    location: "Sunyani, Bono Region",
    established: 2011,
    academicsInfo: "Focused on solving national energy challenges and managing forestry, wildlife, and agricultural natural resources.",
    performanceReview: "Leader in renewable energy research, solar energy installation tests, and forestry tracking systems in West Africa.",
    feesRange: "GH₵ 3,100 - GH₵ 6,900 / year",
    scholarshipsInfo: "UENR Energy Research Fund, environmental NGO grants, and Ministry of Energy scholarships.",
    programsOffered: ["BSc Renewable Energy Engineering", "BSc Natural Resources Management", "BSc Computer Science", "BSc Agricultural Engineering", "BSc Forest Resources Management"],
    admissionRequirements: "WASSCE: Credit passes in English, Core Maths, Integrated Science/Physics, and 3 electives."
  },
  {
    name: "Central University",
    ranking: 11,
    image: "picture/central_campus.jpg",
    type: "Private",
    location: "Miotso, Greater Accra Region",
    established: 1998,
    academicsInfo: "Largest private university in Ghana, owned by the International Central Gospel Church. Broad business, science, humanities, and pharmacy curricula.",
    performanceReview: "Strong industry links in banking and media sectors, with an expansive, well-equipped campus.",
    feesRange: "GH₵ 7,500 - GH₵ 14,000 / year",
    scholarshipsInfo: "ICGC Educational Grants, Central University Financial Aid, and Chancellor's Scholarships.",
    programsOffered: ["Doctor of Pharmacy (PharmD)", "BSc Architecture", "BSc Computer Science", "BBA Human Resource Management", "BSc Nursing"],
    admissionRequirements: "WASSCE: Credits in 6 subjects including Core Mathematics and English. Science electives required for Pharmacy."
  },
  {
    name: "Kumasi Technical University (KsTU)",
    ranking: 12,
    image: "picture/kstu_campus.jpg",
    type: "Public",
    location: "Kumasi, Ashanti Region",
    established: 1954,
    academicsInfo: "Leading vocational-technical education centre in the middle belt of Ghana. Engineering, environment, and business technology.",
    performanceReview: "Excellent output in solar energy training courses and national TVET skills competitions.",
    feesRange: "GH₵ 2,600 - GH₵ 5,000 / year",
    scholarshipsInfo: "KsTU Student Aid, MasterCard Foundation partnership programs, and GETFund local allocations.",
    programsOffered: ["BTech Electrical & Electronic Engineering", "BTech Building Technology", "BTech Computer Science", "BTech Chemical Engineering", "BTech Marketing"],
    admissionRequirements: "WASSCE: 6 credit passes including Maths and English, or Technical School certificates."
  },
  {
    name: "Pentecost University",
    ranking: 13,
    image: "picture/pentecost_campus.jpg",
    type: "Private",
    location: "Sowutuom, Accra",
    established: 2003,
    academicsInfo: "Owned by The Church of Pentecost. Focuses on ethical leadership, business administration, health sciences, and engineering studies.",
    performanceReview: "Strong records in nurse training licensing exams and active international university research partnerships.",
    feesRange: "GH₵ 5,500 - GH₵ 9,500 / year",
    scholarshipsInfo: "Pentecost Church Education Fund, PU Work-Study, and leadership merit grants.",
    programsOffered: ["BSc Nursing", "BSc Physician Assistantship", "BSc Computer Science", "BBA Accounting", "BSc Construction Technology"],
    admissionRequirements: "WASSCE: Credits in English, Core Maths, Science/Social, plus 3 electives."
  },
  {
    name: "Accra Technical University (ATU)",
    ranking: 14,
    image: "picture/atu_campus.jpg",
    type: "Public",
    location: "Barnes Road, Accra",
    established: 1949,
    academicsInfo: "Premier technical university in Ghana focusing on hands-on TVET education, mechanical, civil and electrical engineering, and applied sciences.",
    performanceReview: "Pioneered industrial internship placements and practical machinery training in downtown Accra.",
    feesRange: "GH₵ 2,500 - GH₵ 4,800 / year",
    scholarshipsInfo: "Government TVET scholarships, ATU Staff Welfare loans, and local industrial sponsorships.",
    programsOffered: ["BTech Mechanical Engineering", "BTech Civil Engineering", "BTech Computer Science", "BTech Fashion Design", "BTech Accounting"],
    admissionRequirements: "WASSCE: 6 credit passes including English and Mathematics, or TVET technical certificate credentials."
  },
  {
    name: "Ho Technical University (HTU)",
    ranking: 15,
    image: "picture/ho_campus.jpg",
    type: "Public",
    location: "Ho, Volta Region",
    established: 1968,
    academicsInfo: "Renowned for food science, hospitality management, fashion design, and agricultural engineering technology programs.",
    performanceReview: "Leader in hospitality education, hosting training hotels and advanced culinary test centers.",
    feesRange: "GH₵ 2,200 - GH₵ 4,300 / year",
    scholarshipsInfo: "HTU Financial Aid Scheme, local tourism board grants, and Volta scholarship boards.",
    programsOffered: ["BTech Hospitality & Tourism Management", "BTech Agro-Enterprise Development", "BTech Fashion Design", "BTech Computer Science", "BTech Agricultural Engineering"],
    admissionRequirements: "WASSCE: 6 credit passes including English and Core Mathematics, plus relevant electives."
  },
  {
    name: "Catholic University of Ghana (CUG)",
    ranking: 16,
    image: "picture/catholic_campus.jpg",
    type: "Private",
    location: "Fiapre, Sunyani",
    established: 2003,
    academicsInfo: "Focuses on moral and academic training. Major programs in computer science, public health, nursing, and education.",
    performanceReview: "Recognized for high ethical and professional standards among graduates in local municipal hospitals.",
    feesRange: "GH₵ 5,400 - GH₵ 8,900 / year",
    scholarshipsInfo: "Catholic Secretariat Bursaries, CUG Needy Students Fund, and diocesan educational aids.",
    programsOffered: ["BSc Computer Science", "BSc Public Health", "BSc Economics and Business Administration", "BEd English", "BSc Mathematics & Statistics"],
    admissionRequirements: "WASSCE: 6 credit passes (A1-C6) including Core English and Core Mathematics."
  },
  {
    name: "Takoradi Technical University (TTU)",
    ranking: 18,
    image: "picture/ttu_campus.jpg",
    type: "Public",
    location: "Takoradi, Western Region",
    established: 1954,
    academicsInfo: "Pioneers technical courses for Ghana's petroleum and gas industries. Mechanical engineering, welding technology, and business administration.",
    performanceReview: "Strategically located in the oil hub of Ghana, with heavy corporate placements in offshore drilling firms.",
    feesRange: "GH₵ 2,500 - GH₵ 4,900 / year",
    scholarshipsInfo: "GASSUP Petroleum Scholarships, Takoradi Chamber of Commerce grants, and TVET TVET funding.",
    programsOffered: ["BTech Petroleum Engineering", "BTech Mechanical Engineering", "BTech Electrical Technology", "BTech Procurement Management", "BTech Graphic Design"],
    admissionRequirements: "WASSCE: Credit passes in Mathematics, English, Integrated Science, and 3 science/technical electives."
  },
  {
    name: "Presbyterian University Ghana (PUG)",
    ranking: 21,
    image: "picture/pug_campus.jpg",
    type: "Private",
    location: "Abetifi-Kwahu, Eastern Region",
    established: 2003,
    academicsInfo: "Multi-campus university combining academic excellence with Christian values. Environmental studies, information technology, and nursing.",
    performanceReview: "Consistently ranked as one of the most disciplined and high-quality private universities in Ghana.",
    feesRange: "GH₵ 5,800 - GH₵ 9,800 / year",
    scholarshipsInfo: "Presbyterian Church Scholarship Fund, PUG needy student subsidies, and local community aids.",
    programsOffered: ["BSc Nursing", "BSc Information Technology", "BSc Environmental and Development Studies", "BBA Agribusiness", "BSc Physician Assistantship"],
    admissionRequirements: "WASSCE: 6 credit passes (A1-C6) including core English and Mathematics."
  },
  {
    name: "Cape Coast Technical University (CCTU)",
    ranking: 22,
    image: "picture/cctu_campus.jpg",
    type: "Public",
    location: "Cape Coast, Central Region",
    established: 1984,
    academicsInfo: "Dedicated to engineering, applied sciences, TVET systems, and green energy studies. Promotes sustainable environmental design.",
    performanceReview: "Primary resource center for mechanical, construction, and hospitality vocational training in southern Ghana.",
    feesRange: "GH₵ 2,300 - GH₵ 4,600 / year",
    scholarshipsInfo: "Government TVET support, CCTU Student Aid, and tourism corporate grants.",
    programsOffered: ["BTech Renewable Energy", "BTech Civil Engineering", "BTech Hospitality Management", "BTech Mechanical Engineering", "BTech Computer Science"],
    admissionRequirements: "WASSCE: Credit passes in English, Mathematics, Science, and 3 vocational electives."
  },
  {
    name: "Methodist University Ghana (MUG)",
    ranking: 25,
    image: "picture/methodist_campus.jpg",
    type: "Private",
    location: "Dansoman, Accra",
    established: 2000,
    academicsInfo: "Affiliated with the Methodist Church Ghana. Excellent programs in counseling, psychology, business administration, and accounting.",
    performanceReview: "Noted for its serene campus atmosphere and strong corporate placement department.",
    feesRange: "GH₵ 5,200 - GH₵ 9,000 / year",
    scholarshipsInfo: "Methodist Church Education Fund, MUG Work-Study Program, and local district welfare grants.",
    programsOffered: ["BSc Psychology", "BBA Accounting", "BSc Information Technology", "BA Social Work", "BSc Nursing"],
    admissionRequirements: "WASSCE: Credits in English, Core Maths, Science/Social, plus 3 electives."
  },
  {
    name: "Ashesi University",
    ranking: 27,
    image: "picture/ashesi_campus.jpg",
    type: "Private",
    location: "Berekuso, Eastern Region",
    established: 2002,
    academicsInfo: "A liberal arts college known for its strict honor code, leadership training, critical thinking instruction, and high-impact technology and business courses.",
    performanceReview: "Achieved global acclaim for its student career placements, entrepreneurship incubator, and state-of-the-art green campus.",
    feesRange: "GH₵ 48,000 / year (All-inclusive tuition)",
    scholarshipsInfo: "100% full tuition need-based scholarships, Ashesi Foundation support, and MasterCard Foundation scholarships.",
    programsOffered: ["BSc Computer Science", "BSc Management Information Systems", "BSc Business Administration", "BSc Mechanical Engineering", "BSc Electrical Engineering"],
    admissionRequirements: "WASSCE: Minimum 6 credit passes (A1-C6) including Core Maths and English, plus personal essays and an entrance interview."
  },
  {
    name: "All Nations University (ANU)",
    ranking: 28,
    image: "picture/anu_campus.jpg",
    type: "Private",
    location: "Koforidua, Eastern Region",
    established: 2002,
    academicsInfo: "Highly recognized for engineering and space science programs. Designed and launched Ghana's first educational satellite (Ghanasat-1).",
    performanceReview: "Pioneered space science education and satellite research in West Africa, hosting advanced laboratories.",
    feesRange: "GH₵ 6,000 - GH₵ 10,500 / year",
    scholarshipsInfo: "ANU Space Research Scholarship, leadership grants, and Church sponsorships.",
    programsOffered: ["BSc Electronics & Communications Engineering", "BSc Computer Science", "BSc Biomedical Engineering", "BBA Oil and Gas Management", "BSc Nursing"],
    admissionRequirements: "WASSCE: 6 credits including English, Core Maths, and Science (Physics/Chemistry for engineering)."
  },
  {
    name: "Valley View University (VVU)",
    ranking: 33,
    image: "picture/vvu_campus.jpg",
    type: "Private",
    location: "Oyibi, Greater Accra Region",
    established: 1979,
    academicsInfo: "First private university in Ghana to receive a presidential charter. Values-based education focused on integrity, technology, and health.",
    performanceReview: "Outstanding computer science graduate base with strong ethical code records in local industry.",
    feesRange: "GH₵ 6,500 - GH₵ 10,000 / year",
    scholarshipsInfo: "Seventh-day Adventist Church bursaries, VVU Work-Study programs, and academic excellence scholarships.",
    programsOffered: ["BSc Computer Science", "BSc Information Technology", "BSc Nursing", "BBA Accounting", "BSc Mathematics"],
    admissionRequirements: "WASSCE: Credit passes in 3 core subjects (including Core Maths and English) and 3 electives."
  },
  {
    name: "Regent University College of Science and Technology",
    ranking: 37,
    image: "picture/regent_campus.jpg",
    type: "Private",
    location: "McCarthy Hill, Accra",
    established: 2003,
    academicsInfo: "Pioneered specialized private sector science and ICT education in Accra. Strong networks in engineering, business, and theology studies.",
    performanceReview: "High placements in telecommunications corporations and banking software departments in Accra.",
    feesRange: "GH₵ 5,500 - GH₵ 9,000 / year",
    scholarshipsInfo: "Regent Institutional Aid, telecom corporate bursaries, and merit-based tuition discounts.",
    programsOffered: ["BSc Computer Science", "BSc Information Systems Sciences", "BSc Telecommunications Engineering", "BBA Banking and Finance", "BTh Theology"],
    admissionRequirements: "WASSCE: Credit passes in English, Core Maths, Integrated Science/Physics, and 3 electives."
  },
  {
    name: "Koforidua Technical University (KTU)",
    ranking: 40,
    image: "picture/ktu_campus.jpg",
    type: "Public",
    location: "Koforidua, Eastern Region",
    established: 1997,
    academicsInfo: "Stresses technical skills and entrepreneurship. Heavy programs in computer science, statistics, biomedical engineering, and automotive systems.",
    performanceReview: "Gained national acclaim for building local electric vehicle prototypes and software systems.",
    feesRange: "GH₵ 2,400 - GH₵ 4,500 / year",
    scholarshipsInfo: "KTU Financial Aid Scheme, local mining and technical corporate bursaries.",
    programsOffered: ["BTech Computer Science", "BTech Biomedical Engineering", "BTech Automotive Engineering", "BTech Graphic Design", "BTech Statistics"],
    admissionRequirements: "WASSCE: Credit passes in English, Mathematics, Integrated Science, and 3 related technical electives."
  },
  {
    name: "Lancaster University Ghana",
    ranking: 42,
    image: "picture/lancaster_campus.jpg",
    type: "Private",
    location: "East Legon, Accra",
    established: 2013,
    academicsInfo: "UK-accredited university offering British degree standards locally. Strong focus on business, international relations, law, and computer science.",
    performanceReview: "Excellent global curriculum standards and foreign exchange study opportunities.",
    feesRange: "GH₵ 45,000 - GH₵ 60,000 / year",
    scholarshipsInfo: "Lancaster Global Scholarship, merit-based entry discounts, and international corporate sponsorships.",
    programsOffered: ["BSc Computer Science", "Bachelor of Laws (LLB)", "BSc Business Studies", "BA International Relations", "BSc Accounting & Finance"],
    admissionRequirements: "WASSCE/A-Levels: Minimum 6 credits in WASSCE or 3 B grades in A-levels including Core Mathematics and English."
  },
  {
    name: "BlueCrest University College",
    ranking: 43,
    image: "picture/bluecrest_campus.jpg",
    type: "Private",
    location: "Kokomlemle, Accra",
    established: 1999,
    academicsInfo: "Tech-centric institution with professional certifications built into standard IT, fashion design, and journalism degree programs.",
    performanceReview: "Recognized for practical IT training labs, networking systems certifications, and annual student fashion exhibitions.",
    feesRange: "GH₵ 6,500 - GH₵ 12,000 / year",
    scholarshipsInfo: "BlueCrest Scholarship Foundation, tech talent discount waivers, and school excellence awards.",
    programsOffered: ["BSc Information Technology", "BA Fashion Design", "BSc Journalism & Mass Communication", "BBA Finance", "BSc Software Engineering"],
    admissionRequirements: "WASSCE: Credit passes in English and Core Maths, plus 3 electives. IT electives are an advantage."
  },
  {
    name: "Wisconsin International University College",
    ranking: 44,
    image: "picture/wisconsin_campus.jpg",
    type: "Private",
    location: "Agbogba, Accra",
    established: 2000,
    academicsInfo: "Offers multicultural study environments. Top-tier programs in nursing, law, security management, and business communication.",
    performanceReview: "Popular with international students from Nigeria, Ivory Coast, and Gabon. Houses state-of-the-art simulation law courts.",
    feesRange: "GH₵ 6,200 - GH₵ 11,000 / year",
    scholarshipsInfo: "Wisconsin Institutional Aid, international student bursaries, and merit waivers.",
    programsOffered: ["Bachelor of Laws (LLB)", "BSc Nursing", "BSc IT and Management", "BSc Security & Forensic Studies", "BBA Banking & Finance"],
    admissionRequirements: "WASSCE: Credit passes in Maths, English, Science/Social, and 3 electives. Aggregate total <= 24."
  },
  {
    name: "Academic City University College",
    ranking: 45,
    image: "picture/academiccity_campus.jpg",
    type: "Private",
    location: "Haatso, Accra",
    established: 2017,
    academicsInfo: "Innovative university utilizing modern project-based learning. Specializes in advanced engineering, artificial intelligence, robotics, and design thinking.",
    performanceReview: "Equipped with the first real engineering makerspace in a private college in Ghana. High student startup incubation output.",
    feesRange: "GH₵ 25,000 - GH₵ 35,000 / year",
    scholarshipsInfo: "Academic City President's Scholarship, need-based tuition waivers, and tech talent bursaries.",
    programsOffered: ["BSc Artificial Intelligence", "BSc Robotics Engineering", "BSc Computer Engineering", "BSc Entrepreneurship", "BSc Journalism & Mass Communication"],
    admissionRequirements: "WASSCE: Credits in Core Maths, English, Integrated Science, and 3 electives (Physics, Elective Maths, Chemistry for Engineering)."
  },
  {
    name: "Webster University Ghana",
    ranking: 51,
    image: "picture/webster_campus.jpg",
    type: "Private",
    location: "East Legon, Accra",
    established: 2013,
    academicsInfo: "American-accredited university offering US degrees in Ghana. Specializes in international relations, media communications, and management.",
    performanceReview: "Features highly diverse classrooms, international exchange programs, and study-abroad options to Webster USA and Europe.",
    feesRange: "GH₵ 50,000 - GH₵ 70,000 / year",
    scholarshipsInfo: "Webster Legacy Scholarships, US federal aid eligibility (FAFSA), and local merit bursaries.",
    programsOffered: ["BA International Relations", "BA Media Communications", "BSc Business Administration", "BS Computer Science", "BA Psychology"],
    admissionRequirements: "WASSCE/SAT: Credits in English and Maths, plus SAT/ACT score submission for American standards."
  }
];
